### ISSUE TITLE
partyIdSet (and other sets) in get#FullCalendarData.

### ISSUE THREAD

**Issue by ronankeane** [moqui/mantle#72] opened 2015-10-07 07:39 UTC
This field is not working in the econdition for the main entity-find for this service. 
Reason seems to be the list brackets (It was showing [[partyId1, partyId2...]] in my log message.).
To make it work, I added partyIdSet = partyIdSet.toString().replace("[", "").replace("]", "").replace(" ", "") to the script run on condition="partyIdList", as an improvised fix.

**Comment by jonesde** [comment] 2015-10-07 15:44
Which get#FullCalendarData service are you talking about, the one in mantle.work.EventServices or mantle.work.TaskServices? Do you mean the partyIdList parameter and other *List parameters, or something else? Looking at those *List parameters I noticed they don't have a type="List" and so would be converted to a String, not what is intended for them. I'll commit a fix for that.

Otherwise this issue is very unclear: no usage scenario and what happened versus what should happen, and no details that match specific services or parameters (leaving me to guess). For that reason I'm closing this issue, please open another with more details and that is reproducible if needed (especially if adding type="List" to each of the List parameters doesn't resolve whatever your issue is).

**Closed by jonesde** 2015-10-07 15:44 UTC
